# Generated by Django 5.0.1 on 2024-03-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_stu_admit_duration_stu_admit_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_admit',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stu_admit',
            name='next_followup_date',
            field=models.DateField(null=True),
        ),
    ]
