# Generated by Django 5.0.1 on 2024-04-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_alter_stu_admit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_admit',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='course_master',
            name='fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
