# Generated by Django 5.0.1 on 2024-04-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_remove_stu_admit_sub_category_course_master_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stu_admit',
            old_name='name',
            new_name='stu_name',
        ),
    ]
