# Generated by Django 5.0.1 on 2024-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_rename_name_stu_admit_stu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(null=True)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('balance_till', models.IntegerField(blank=True, default=0, null=True)),
                ('fees_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('now_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('total_balance_pending', models.IntegerField(blank=True, default=0, null=True)),
                ('next_follow_up_date', models.DateField(null=True)),
            ],
        ),
    ]
