# Generated by Django 5.0.1 on 2024-04-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_fee_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_followup',
            name='student_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.stu_admit'),
        ),
    ]
