# Generated by Django 5.0.1 on 2024-04-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_rename_student_name_fee_followup_stu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee_followup',
            old_name='stu_name',
            new_name='student_name',
        ),
    ]
