# Generated by Django 5.0.2 on 2024-04-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0021_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
